config:
  L: 200
  batch_size: 64
  checkpoint_dir: .\
  classifier_im_size:
  - 64
  - 64
  lr: 2.5e-05
  model_name: DDIM
  num_epochs: 2000
  num_epochs_cls: 1000
  pretrained_dir: .\pretrained
  s: 6
  seed: 42
  split_dir: .\data\splits
  target_size:
  - 128
  - 128
