model_name: DDIM

seed: 42

split_dir: .\data\splits

target_size: !<tag:yaml.org,2002:seq> [64,64]
batch_size: 32

pretrained_dir: .\pretrained
ddim_log_dir: .\logs\my_logs_ddim
classifier_log_dir: .\logs\my_logs_classifier
classifier_dec_log_dir: .\logs\my_logs_classifier_dec  # trained with decathlon dataset

lr: 2.5e-5
lr_cls: 7.5e-5
num_epochs: 1000
num_epochs_cls: 1000
early_stopping: 50

# classifier_lr: 2.5e-5
# classifier_num_epochs: 1000
classifier_im_size: [64, 64]

L: 200  # noise-level
s: 50   # gradient scale
